spring:
  datasource:
    url: jdbc:postgresql://postgres:${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  sql:
    init:
      mode: always


#${} --> environment variable

